CREATE TABLE IF NOT EXISTS `USERS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `email` MEDIUMTEXT NULL DEFAULT NULL,
  `password` MEDIUMTEXT NULL DEFAULT NULL,
  `name` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `GROUPS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NULL DEFAULT NULL,
  `owner` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `TASKS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NULL DEFAULT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `owner` INTEGER NULL DEFAULT NULL,
  `group` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `MEMBERSHIPS` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `group` INTEGER NULL DEFAULT NULL,
  `user` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `ASSIGNMENTS`(
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `task` INTEGER NULL DEFAULT NULL,
  `user` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

ALTER TABLE `TASKS` ADD FOREIGN KEY (`owner`) REFERENCES `USERS` (`id`);
ALTER TABLE `TASKS` ADD FOREIGN KEY (`group`) REFERENCES `GROUPS` (`id`);
ALTER TABLE `MEMBERSHIPS` ADD FOREIGN KEY (`group`) REFERENCES `GROUPS` (`id`);
ALTER TABLE `MEMBERSHIPS` ADD FOREIGN KEY (`user`) REFERENCES `USERS` (`id`);
ALTER TABLE `ASSIGNMENTS` ADD FOREIGN KEY (`task`) REFERENCES `TASKS` (`id`);
ALTER TABLE `ASSIGNMENTS` ADD FOREIGN KEY (`user`) REFERENCES `USERS` (`id`);
